replicaCount: 1

image:
  repository: $repository
  tag: "$tag"
  pullPolicy: Always

extraLabels:
  "ID": "$service_id"

gitlab:
  app: "$app_name"
  envURL: "$repo_url"

service:
  enabled: true
  name: "web"
  url: "$public_url"
  type: ClusterIP
  externalPort: 3000
  internalPort: 3000

ingress:
  # disable ingress to not overwrite manual `anubis` setup in `rancher`.
  enabled: false

livenessProbe:
  path: /
  initialDelaySeconds: 15
  timeoutSeconds: 15
  scheme: "HTTP"
  probeType: "httpGet"

readinessProbe:
  path: /
  initialDelaySeconds: 5
  timeoutSeconds: 3
  scheme: "HTTP"
  probeType: "httpGet"
